### ISSUE TITLE
on.musicStart() doesnt exist

### ISSUE THREAD

**Issue by Dope699** [Ayush4385/Aoi.js-bot#5]
error

**Comment by TreeWarrior0** [comment]
same

**Comment by Ayush4385** [comment]
Sorry for replying very late,I was a bit busy so I didn't saw this issue.let me check and fix it :D

**Comment by Ayush4385** [comment]
@Dope699 I will fix it soon

**Comment by Ayush4385** [comment]
@Dope699 can you try now?I have made a bit changes

**Comment by Dope699** [comment]
thanks :D

**Comment by Ayush4385** [comment]
@Dope699 Ig your problem is now solved so I am closing this issue.If you have any other problem then you can join discord server or make a new issue.
